#å…è´¹æœåŠ¡å™¨åœ°å€ é…ç½®ç¤ºä¾‹ é…ç½®å¤šä¸ªåˆ«å¿˜äº†copy "-"
#usernameï¼š è´¦å·ï¼Œ passwordï¼š å¯†ç ï¼Œ typeï¼š 0 é˜¿è´äº‘ï¼Œ 1ä¸‰ä¸°äº‘
cloudServers:
  -
    username: 13185888688
    password: 13465789
    type: 0
  -
    username: 13185888688
    password: 13465789
    type: 1
#  -
#    username: 13111001111
#    password: 123456789
#    type: 1


#é‚®ç®±é…ç½®
mailInfo:
  #é‚®ä»¶æœåŠ¡å™¨  ä½œè€…ä½¿ç”¨çš„QQé‚®ç®±ï¼Œ
  serverHost: smtp.qq.com
  serverPort: 465
  username: 132456789@qq.com
  #ä½¿ç”¨QQé‚®ç®±æ³¨æ„,è¿™é‡Œçš„å¯†ç å¹¶ä¸æ˜¯QQé‚®ç®±å¯†ç   éœ€è¦è‡ªå·±å¼€å¯smtpæœåŠ¡å™¨,QQé‚®ç®±ä¼šç»™ä½ ä¸€ä¸²å¯†ç 
  password: bpmgyuujdcpcjfbb
  #æ”¶ä»¶äººé‚®ç®±  è¿™é‡Œæˆ‘ç”¨çš„QQé‚®ç®±,å…³æ³¨å…¬ä¼—å·,å¾®ä¿¡å¯ä»¥ç›´æ¥æ”¶åˆ°é€šçŸ¥
  receiveUser: 123456789@qq.com


#åšå®¢é…ç½® GitHub ä¸ªäººåšå®¢
blogInfo:
  #è¿™é‡Œæä¾›äº†ä¸€ä¸ªå…¬å…±çš„(æ–°æ³¨å†Œäº†ä¸€ä¸ªè´¦å·æ­å»ºçš„,æ€•æŠŠæˆ‘åŸæ¥çš„ç»™å°äº†ğŸ’©ï¸)
  #æ¨èä½¿ç”¨è‡ªå·±æ­å»ºçš„GitHub Pages å¤šä¸ªåšå®¢æ–‡ä»¶åŒæ—¶æäº¤,æ ¼å¼åŒ–ä¸ºhtmlå¯èƒ½ç”¨æ—¶è¾ƒä¹…  å¯¼è‡´ç¨‹åºè¶…æ—¶ä»è€Œå»¶æœŸå¤±è´¥
  #æ ¼å¼: git@github.com:{ç”¨æˆ·å}/{ç”¨æˆ·å(å…¨ä¸ºå°å†™)}.github.io.git
  uri: git@github.com:Demo-AD/demo-ad.github.io.git
  #ä»“åº“æ‹‰å–åˆ°æœ¬åœ°æ—¶çš„è·¯å¾„
  localPath: /freeServer/repo
  #å¦‚æœä½¿ç”¨æˆ‘æä¾›çš„GitHub Pages,è¿™é‡Œæœ€å¥½å¡«å†™ä½ çš„githubç”¨æˆ·å å¯ä»¥é˜²æ­¢å‘å¸ƒæ–‡ç« åœ°å€å†²çª
  username: Demo-Liu

#PhantomJs é…ç½®é¡¹
phantomJs:
  #phantomJs è·¯å¾„  windows å’Œ Linux x86_64å·²ç»åµŒå…¥äº†é¡¹ç›®,å…¶å®ƒç³»ç»Ÿè¯·è‡ªè¡Œé…ç½®æ­¤é¡¹
  phantomJsExec:
  #å›¾ç‰‡ç”Ÿæˆè·¯å¾„
  picPath: /freeServer/phantomJsPic/postpone.png

#ç³»ç»Ÿé…ç½®
#åšå®¢åˆå§‹åŒ–ç­‰å¾…æ¬¡æ•° å¦‚æœä½¿ç”¨ä½œè€…æä¾›çš„å…¬ç”¨ä»“åº“, æœ€å¥½æŠŠåˆå§‹åŒ–ç­‰å¾…æ—¶é—´è°ƒå¤§ä¸€ç‚¹  å»ºè®®ä¸ºåŠå°æ—¶ä»¥å†…
blogInitWaitCount: 10
#åšå®¢åˆå§‹åŒ–ç­‰å¾…æ—¶é—´(åˆ†é’Ÿ)
blogInitWaitTime: 1

#èµ„æºæ–‡ä»¶æå–è·¯å¾„
resourceTempFilePath: /freeServer/resource
